### ISSUE TITLE
Errors/warnings on build

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#3439]
I imagine these are spurious errors or warnings, but there are many of each and they are (at least) distracting when building...

1. `You must first call texture() before using vertex() with image based u and v coordinates`
2. `(node:43277) UnhandledPromiseRejectionWarning: Error: Protocol error` `(Runtime.callFunctionOn): Object reference chain is too long`

<details>

```
Running "yuidoc:prod" (yuidoc) task
Failed to find lines for { name: 'Shape',
  submodules: 
   { '2D Primitives': 1,
     Curves: 1,
     Vertex: 1,
     '3D Primitives': 1,
     '3D Models': 1 },
  elements: {},
  classes: {},
  fors: { p5: 1 },
  namespaces: {} }
Failed to find lines for { name: 'Events',
  submodules: { Acceleration: 1, Keyboard: 1, Mouse: 1, Touch: 1 },
  elements: {},
  classes: {},
  fors: { p5: 1 },
  namespaces: {} }
src/io/files.js:1388: method p5.save missing example
src/webgl/material.js:151: method p5.shader missing example
src/webgl/p5.Camera.js:187: method p5.createCamera missing example
src/webgl/p5.Camera.js:298: method p5.Camera.perspective missing example
src/webgl/p5.Camera.js:380: method p5.Camera.ortho missing example
src/webgl/p5.Camera.js:671: method p5.Camera.camera missing example
src/webgl/p5.Geometry.js:50: method p5.Geometry.computeFaces missing example
src/webgl/p5.Geometry.js:92: method p5.Geometry.computeNormals missing example
src/webgl/p5.Geometry.js:131: method p5.Geometry.averageNormals missing example
src/webgl/p5.Geometry.js:152: method p5.Geometry.averagePoleNormals missing example
src/webgl/p5.Geometry.js:245: method p5.Geometry.normalize missing example
src/webgl/p5.Shader.js:274: method p5.Shader.setUniform missing example
Start YUIDoc compile...
Scanning: src/, lib/addons/
Output: docs/reference/
YUIDoc compile completed in 2.885 seconds

Running "clean:reference" (clean) task
>> 5 paths cleaned.

Running "minjson:compile" (minjson) task
File "docs/reference/data.min.json" created: 1.44 MB → 985.96 kB

Running "eslint:build" (eslint) task

Running "eslint:source" (eslint) task

Running "eslint:test" (eslint) task

Running "eslint-samples:source" (eslint-samples) task

Running "browserify" task
>> Bundle lib/p5.js created.

Running "browserify:min" (browserify) task
>> Bundle lib/p5.pre-min.js created.

Running "uglify:dist" (uglify) task
>> 2 files created 1.71 MB → 479.15 kB

Running "connect:server" (connect) task
Started connect web server on http://localhost:9001

Running "mochaChrome:yui" (mochaChrome) task



  src/color/creating_reading.js
    alpha documentation
      ✓ example #1 works
    blue documentation
220
      ✓ example #1 works
    brightness documentation
      ✓ example #1 works
    color documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
      ✓ example #5 works
      ✓ example #6 works
      ✓ example #7 works
      ✓ example #8 works
    green documentation
75
      ✓ example #1 works
    hue documentation
      ✓ example #1 works
    lerpColor documentation
      ✓ example #1 works
    lightness documentation
      ✓ example #1 works
    red documentation
255
      ✓ example #1 works
0.4980392156862745
      ✓ example #2 works
    saturation documentation
      ✓ example #1 works
  src/color/p5.Color.js
    toString documentation
      ✓ example #1 works
    setRed documentation
      ✓ example #1 works
    setGreen documentation
      ✓ example #1 works
    setBlue documentation
      ✓ example #1 works
    setAlpha documentation
      ✓ example #1 works
  src/color/setting.js
    background documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
      ✓ example #5 works
      ✓ example #6 works
      ✓ example #7 works
      ✓ example #8 works
      ✓ example #9 works
      ✓ example #10 works
      ✓ example #11 works
    clear documentation
      ✓ example #1 works
    colorMode documentation
      ✓ example #1 works (236ms)
      ✓ example #2 works (274ms)
      ✓ example #3 works
      ✓ example #4 works
    fill documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
      ✓ example #5 works
      ✓ example #6 works
      ✓ example #7 works
      ✓ example #8 works
      ✓ example #9 works
      ✓ example #10 works
      ✓ example #11 works
    noFill documentation
      ✓ example #1 works
p5.RendererGL: enabled webgl context
      ✓ example #2 works (73ms)
    noStroke documentation
      ✓ example #1 works
p5.RendererGL: enabled webgl context
      ✓ example #2 works
    stroke documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
      ✓ example #5 works
      ✓ example #6 works
      ✓ example #7 works
      ✓ example #8 works
      ✓ example #9 works
      ✓ example #10 works
      ✓ example #11 works
  src/core/shape/2d_primitives.js
    arc documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
      ✓ example #5 works
    ellipse documentation
      ✓ example #1 works
    circle documentation
      ✓ example #1 works
    line documentation
      ✓ example #1 works
      ✓ example #2 works
    point documentation
      ✓ example #1 works
    quad documentation
      ✓ example #1 works
    rect documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    square documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    triangle documentation
      ✓ example #1 works
  src/core/shape/attributes.js
    ellipseMode documentation
      ✓ example #1 works
      ✓ example #2 works
    noSmooth documentation
      ✓ example #1 works
    rectMode documentation
      ✓ example #1 works
      ✓ example #2 works
    smooth documentation
      ✓ example #1 works
    strokeCap documentation
      ✓ example #1 works
    strokeJoin documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    strokeWeight documentation
      ✓ example #1 works
  src/core/shape/curves.js
    bezier documentation
      ✓ example #1 works
      ✓ example #2 works
    bezierDetail documentation
p5.RendererGL: enabled webgl context
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
      ✓ example #1 works (51ms)
    bezierPoint documentation
      ✓ example #1 works
    bezierTangent documentation
      ✓ example #1 works
      ✓ example #2 works
    curve documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    curveDetail documentation
p5.RendererGL: enabled webgl context
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
      ✓ example #1 works (64ms)
    curveTightness documentation
      ✓ example #1 works
    curvePoint documentation
      ✓ example #1 works
    curveTangent documentation
      ✓ example #1 works
  src/core/shape/vertex.js
    beginContour documentation
      ✓ example #1 works
    beginShape documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
      ✓ example #5 works
      ✓ example #6 works
      ✓ example #7 works
      ✓ example #8 works
      ✓ example #9 works
      ✓ example #10 works
      ✓ example #11 works
    bezierVertex documentation
      ✓ example #1 works
      ✓ example #2 works
p5.RendererGL: enabled webgl context
p5.RendererGL: enabled webgl context
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
You must first call texture() before using vertex() with image based u and v coordinates
      ✓ example #3 works (365ms)
    curveVertex documentation
      ✓ example #1 works
    endContour documentation
      ✓ example #1 works
    endShape documentation
      ✓ example #1 works
    quadraticVertex documentation
      ✓ example #1 works
      ✓ example #2 works
    vertex documentation
      ✓ example #1 works
      ✓ example #1 works
  src/core/constants.js
    HALF_PI documentation
    PI documentation
      ✓ example #1 works
    QUARTER_PI documentation
      ✓ example #1 works
    TAU documentation
      ✓ example #1 works
      ✓ example #1 works
    TWO_PI documentation
    DEGREES documentation
      ✓ example #1 works
    RADIANS documentation
      ✓ example #1 works
  src/core/environment.js
    print documentation
The value of x is 10
      ✓ example #1 works
    frameCount documentation
      ✓ example #1 works
    focused documentation
      ✓ example #1 works
    cursor documentation
      ✓ example #1 works
    frameRate documentation
      ✓ example #1 works
    noCursor documentation
      ✓ example #1 works
    displayWidth documentation
      ✓ example #1 works
    displayHeight documentation
      ✓ example #1 works
      ✓ example #1 works
    windowWidth documentation
    windowHeight documentation
      ✓ example #1 works
    windowResized documentation
      ✓ example #1 works
    fullscreen documentation
      ✓ example #1 works
    pixelDensity documentation
      ✓ example #1 works
      ✓ example #2 works
    displayDensity documentation
      ✓ example #1 works
    getURL documentation
      ✓ example #1 works
    getURLPath documentation
      ✓ example #1 works
  src/core/main.js
    preload documentation
      ✓ example #1 works (67ms)
      ✓ example #1 works
      ✓ example #1 works
    setup documentation
    draw documentation
    remove documentation
      ✓ example #1 works
  src/core/p5.Element.js
    elt documentation
      ✓ example #1 works
    parent documentation
      ✓ example #1 works
      ✓ example #2 works
    id documentation
      ✓ example #1 works
    class documentation
      ✓ example #1 works
    mousePressed documentation
      ✓ example #1 works
    doubleClicked documentation
      ✓ example #1 works
    mouseWheel documentation
      ✓ example #1 works
    mouseReleased documentation
      ✓ example #1 works
    mouseClicked documentation
      ✓ example #1 works
    mouseMoved documentation
      ✓ example #1 works
    mouseOver documentation
      ✓ example #1 works
    mouseOut documentation
      ✓ example #1 works
    touchStarted documentation
      ✓ example #1 works
    touchMoved documentation
      ✓ example #1 works
    touchEnded documentation
      ✓ example #1 works
    dragOver documentation
      ✓ example #1 works
    dragLeave documentation
      ✓ example #1 works
    drop documentation
      ✓ example #1 works
      ✓ example #2 works
  src/core/p5.Graphics.js
    remove documentation
      ✓ example #1 works
      ✓ example #2 works
  src/core/rendering.js
    createCanvas documentation
      ✓ example #1 works
    resizeCanvas documentation
      ✓ example #1 works
    noCanvas documentation
      ✓ example #1 works
    createGraphics documentation
      ✓ example #1 works
    blendMode documentation
      ✓ example #1 works
      ✓ example #2 works
  src/core/structure.js
    noLoop documentation
      ✓ example #1 works
      ✓ example #2 works
    loop documentation
      ✓ example #1 works
    push documentation
      ✓ example #1 works
      ✓ example #2 works
    pop documentation
      ✓ example #1 works
      ✓ example #2 works
    redraw documentation
      ✓ example #1 works
      ✓ example #2 works
  src/core/transform.js
    applyMatrix documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
    resetMatrix documentation
      ✓ example #1 works
    rotate documentation
      ✓ example #1 works
    rotateX documentation
p5.RendererGL: enabled webgl context
      ✓ example #1 works (42ms)
    rotateY documentation
p5.RendererGL: enabled webgl context
      ✓ example #1 works
    rotateZ documentation
p5.RendererGL: enabled webgl context
      ✓ example #1 works
      ✓ example #1 works
    scale documentation
      ✓ example #2 works
      ✓ example #1 works
    shearX documentation
    shearY documentation
      ✓ example #1 works
      ✓ example #1 works
    translate documentation
      ✓ example #2 works
      ✓ example #3 works
  src/data/p5.TypedDict.js
    createStringDict documentation
true
true
      ✓ example #1 works
    createNumberDict documentation
true
true
      ✓ example #1 works
    size documentation
3
      ✓ example #1 works
    hasKey documentation
true
      ✓ example #1 works
    get documentation
true
      ✓ example #1 works
    set documentation
key:p5 value:JS
      ✓ example #1 works
    create documentation
key:p5 value:js
key:happy value:coding
      ✓ example #1 works
    clear documentation
true
false
      ✓ example #1 works
    remove documentation
key:p5 value:js
key:happy value:coding
key:happy value:coding
      ✓ example #1 works
    print documentation
key:p5 value:js
key:happy value:coding
      ✓ example #1 works
    saveTable documentation
      ✓ example #1 works
    saveJSON documentation
      ✓ example #1 works
    add documentation
7
      ✓ example #1 works
    sub documentation
3
      ✓ example #1 works
    mult documentation
8
      ✓ example #1 works
    div documentation
4
      ✓ example #1 works
    minValue documentation
-10
      ✓ example #1 works
    maxValue documentation
3
      ✓ example #1 works
    minKey documentation
1.2
      ✓ example #1 works
    maxKey documentation
4
      ✓ example #1 works
  src/events/acceleration.js
    accelerationX documentation
      ✓ example #1 works (51ms)
    accelerationY documentation
      ✓ example #1 works
    accelerationZ documentation
      ✓ example #1 works
    rotationX documentation
p5.RendererGL: enabled webgl context
      ✓ example #1 works (55ms)
    rotationY documentation
p5.RendererGL: enabled webgl context
      ✓ example #1 works
    rotationZ documentation
p5.RendererGL: enabled webgl context
      ✓ example #1 works
    pRotationX documentation
clockwise
      ✓ example #1 works
    pRotationY documentation
clockwise
      ✓ example #1 works
    pRotationZ documentation
clockwise
      ✓ example #1 works
    turnAxis documentation
      ✓ example #1 works
    setMoveThreshold documentation
      ✓ example #1 works
    setShakeThreshold documentation
      ✓ example #1 works
      ✓ example #1 works
    deviceMoved documentation
    deviceTurned documentation
      ✓ example #1 works
      ✓ example #2 works
    deviceShaken documentation
      ✓ example #1 works
  src/events/keyboard.js
    keyIsPressed documentation
      ✓ example #1 works
    key documentation
      ✓ example #1 works
    keyCode documentation
      ✓ example #1 works
    keyPressed documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    keyReleased documentation
      ✓ example #1 works
    keyTyped documentation
      ✓ example #1 works
    keyIsDown documentation
      ✓ example #1 works
      ✓ example #2 works
  src/events/mouse.js
    mouseX documentation
      ✓ example #1 works
    mouseY documentation
      ✓ example #1 works
    pmouseX documentation
0 -> 0
      ✓ example #1 works
    pmouseY documentation
0 -> 0
      ✓ example #1 works
    winMouseX documentation
      ✓ example #1 works
    winMouseY documentation
      ✓ example #1 works
    pwinMouseX documentation
      ✓ example #1 works
    pwinMouseY documentation
      ✓ example #1 works
    mouseButton documentation
0
      ✓ example #1 works
    mouseIsPressed documentation
false
      ✓ example #1 works
    mouseMoved documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    mouseDragged documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    mousePressed documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    mouseReleased documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    mouseClicked documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    doubleClicked documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    mouseWheel documentation
      ✓ example #1 works
  src/events/touch.js
    touches documentation
      ✓ example #1 works
    touchStarted documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    touchMoved documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    touchEnded documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
  src/image/image.js
    createImage documentation
      ✓ example #1 works (81ms)
      ✓ example #2 works
      ✓ example #3 works
    saveFrames documentation
      ✓ example #1 works
  src/image/loading_displaying.js
    loadImage documentation
      ✓ example #1 works
      ✓ example #2 works
    image documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
    tint documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    noTint documentation
      ✓ example #1 works
    imageMode documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
  src/image/p5.Image.js
    width documentation
      ✓ example #1 works
    height documentation
      ✓ example #1 works
    pixels documentation
      ✓ example #1 works
      ✓ example #2 works (116ms)
    loadPixels documentation
      ✓ example #1 works
    updatePixels documentation
      ✓ example #1 works
    get documentation
      ✓ example #1 works
    set documentation
      ✓ example #1 works
    resize documentation
      ✓ example #1 works
    copy documentation
      ✓ example #1 works
    mask documentation
      ✓ example #1 works
    filter documentation
      ✓ example #1 works
    blend documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    save documentation
      ✓ example #1 works
    p5.Image documentation
      ✓ example #1 works
  src/image/pixels.js
    pixels documentation
      ✓ example #1 works (112ms)
    blend documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    copy documentation
      ✓ example #1 works
    filter documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
      ✓ example #4 works
      ✓ example #5 works
      ✓ example #6 works (43ms)
      ✓ example #7 works (58ms)
      ✓ example #8 works
    get documentation
      ✓ example #1 works
      ✓ example #2 works
    loadPixels documentation
      ✓ example #1 works
    set documentation
      ✓ example #1 works
      ✓ example #2 works
      ✓ example #3 works
    updatePixels documentation
      ✓ example #1 works
  src/io/files.js
    loadJSON documentation
      ✓ example #1 works (657ms)
      ✓ example #2 works
    loadStrings documentation
      ✓ example #1 works
      ✓ example #2 works
    loadTable documentation
3 total rows in table
3 total columns in table
0
Capra hircus
Goat
1
Panthera pardus
Leopard
2
Equus zebra
Zebra
      ✓ example #1 works (71ms)
[ 'Goat', 'Leopard', 'Zebra' ]
    loadXML documentation
0, Capra hircus, Goat
1, Panthera pardus, Leopard
2, Equus zebra, Zebra
      ✓ example #1 works
    loadBytes documentation
3c
3f
78
6d
6c
      ✓ example #1 works
    httpGet documentation
      ✓ example #1 works
    httpPost documentation
      ✓ example #1 works
      ✓ example #2 works
    httpDo documentation
      ✓ example #1 works
    createWriter documentation
      ✓ example #1 works
    saveJSON documentation
      ✓ example #1 works
    saveStrings documentation
      ✓ example #1 works
    saveTable documentation
      ✓ example #1 works
  src/io/p5.Table.js
    addRow documentation
0
Capra hircus
Goat
1
Panthera pardus
Leopard
2
Equus zebra
Zebra
3
Canis Lupus
Wolf
      ✓ example #1 works
    removeRow documentation
1
Panthera pardus
Leopard
2
Equus zebra
Zebra
      ✓ example #1 works
    getRow documentation
1
Panthera pardus
Leopard
      ✓ example #1 works
    getRows documentation
0
Capra hircus
Unicorn
1
Panthera pardus
Unicorn
2
Equus zebra
Unicorn
      ✓ example #1 works
    findRow documentation
Equus zebra
      ✓ example #1 works
    findRows documentation
2 Goats found
      ✓ example #1 works
    matchRow documentation
Panthera pardus
      ✓ example #1 works
    matchRows documentation
Snake: Reptile
Lizard: Reptile
      ✓ example #1 works
    getColumn documentation
      ✓ example #1 works
[ 'Capra hircus', 'Panthera pardus', 'Equus zebra' ]
    clearRows documentation
0 total rows in table
3 total columns in table
      ✓ example #1 works
    addColumn documentation
0
Capra hircus
Goat
no
1
Panthera pardus
Leopard
yes
2
Equus zebra
Zebra
no
      ✓ example #1 works
    getColumnCount documentation
      ✓ example #1 works
    getRowCount documentation
      ✓ example #1 works
    removeTokens documentation
      ✓ example #1 works
    trim documentation
      ✓ example #1 works
[ [ 'Lion', 'Mammal' ], [ 'Snake', 'Reptile' ] ]
[ [ 'Lion,', 'Mammal' ], [ 'Snake', 'Reptile' ] ]
    removeColumn documentation
2
      ✓ example #1 works
    set documentation
0
Canis Lupus
Wolf
1
Panthera pardus
Leopard
2
Equus zebra
Zebra
      ✓ example #1 works
    setNum documentation
      ✓ example #1 works
[ '0', 1, '2' ]
    setString documentation
      ✓ example #1 works
[ [ '0', 'Capra hircus', 'Goat' ],
  [ '1', 'Panthera pardus', 'Leopard' ],
  [ '2', 'Equus zebra', 'Zebra' ],
  [ '3', 'Canis Lupus', 'Wolf' ] ]
    get documentation
Capra hircus
Capra hircus
      ✓ example #1 works
    getNum documentation
101
      ✓ example #1 works
    getString documentation
0
Capra hircus
Goat
1
Panthera pardus
Leopard
2
Equus zebra
Zebra
      ✓ example #1 works
    getObject documentation
      ✓ example #1 works
    getArray documentation
{ '0': { id: '0', species: 'Capra hircus', name: 'Goat' },
  '1': { id: '1', species: 'Panthera pardus', name: 'Leopard' },
  '2': { id: '2', species: 'Equus zebra', name: 'Zebra' } }
      ✓ example #1 works
[ '0', 'Capra hircus', 'Goat' ]
  src/io/p5.TableRow.js
    set documentation
[ '1', 'Panthera pardus', 'Leopard' ]
[ '2', 'Equus zebra', 'Zebra' ]
      ✓ example #1 works
    setNum documentation
[ [ '0', 'Capra hircus', 'Unicorn' ],
  [ '1', 'Panthera pardus', 'Unicorn' ],
  [ '2', 'Equus zebra', 'Unicorn' ] ]
      ✓ example #1 works
[ [ 10, 'Capra hircus', 'Goat' ],
  [ 11, 'Panthera pardus', 'Leopard' ],
  [ 12, 'Equus zebra', 'Zebra' ] ]
    setString documentation
      ✓ example #1 works
[ [ '0', 'Capra hircus', 'A Goat named George' ],
  [ '1', 'Panthera pardus', 'A Leopard named George' ],
  [ '2', 'Equus zebra', 'A Zebra named George' ] ]
    get documentation
      ✓ example #1 works
    getNum documentation
[ 'Goat', 'Leopard', 'Zebra' ]
minimum id = 0, maximum id = -Infinity
      ✓ example #1 works
    getString documentation
longest: Panthera pardus
      ✓ example #1 works
  src/io/p5.XML.js
    getParent documentation
mammals
      ✓ example #1 works
    getName documentation
mammals
      ✓ example #1 works
    setName documentation
mammals
fish
      ✓ example #1 works
    hasChildren documentation
true
      ✓ example #1 works
    listChildren documentation
      ✓ example #1 works
    getChildren documentation
[ '#text', 'animal', '#text', 'animal', '#text', 'animal', '#text' ]
Goat
Leopard
Zebra
      ✓ example #1 works
    getChild documentation
Goat
      ✓ example #1 works
Leopard
      ✓ example #2 works
    addChild documentation
Platypus
      ✓ example #1 works
    removeChild documentation
Leopard
Zebra
      ✓ example #1 works
Goat
Zebra
      ✓ example #2 works
    getAttributeCount documentation
2
      ✓ example #1 works
    listAttributes documentation
      ✓ example #1 works
[ 'id', 'species' ]
    hasAttribute documentation
true
false
      ✓ example #1 works
    getNum documentation
0
      ✓ example #1 works
    getString documentation
Capra hircus
      ✓ example #1 works
    setAttribute documentation
Capra hircus
Jamides zebra
      ✓ example #1 works
    getContent documentation
Goat
      ✓ example #1 works
    setContent documentation
Goat
Mountain Goat
      ✓ example #1 works
    serialize documentation
<mammals>
  <animal id="0" species="Capra hircus">Goat</animal>
  <animal id="1" species="Panthera pardus">Leopard</animal>
  <animal id="2" species="Equus zebra">Zebra</animal>
</mammals>
      ✓ example #1 works
    p5.XML documentation
0, Capra hircus, Goat
1, Panthera pardus, Leopard
2, Equus zebra, Zebra
      ✓ example #1 works
  src/math/calculation.js
    abs documentation
-3
3
      ✓ example #1 works
    ceil documentation
      ✓ example #1 works
    constrain documentation
      ✓ example #1 works
    dist documentation
      ✓ example #1 works
    exp documentation
      ✓ example #1 works
    floor documentation
      ✓ example #1 works
    lerp documentation
      ✓ example #1 works
    log documentation
      ✓ example #1 works
    mag documentation
36.05551275463989
85.44003745317531
72.80109889280519
106.3014581273465
      ✓ example #1 works
    map documentation
      ✓ example #1 works
      ✓ example #2 works
    max documentation
      ✓ example #1 works
    min documentation
      ✓ example #1 works
    norm documentation
      ✓ example #1 works
    pow documentation
      ✓ example #1 works
    round documentation
      ✓ example #1 works
    sq documentation
      ✓ example #1 works
    sqrt documentation
      ✓ example #1 works
  src/math/math.js
    createVector documentation
p5.RendererGL: enabled webgl context
      ✓ example #1 works (103ms)
  src/math/noise.js
    noise documentation
      ✓ example #1 works
      ✓ example #2 works
    noiseDetail documentation
      ✓ example #1 works (227ms)
    noiseSeed documentation
      ✓ example #1 works
  src/math/p5.Vector.js
    toString documentation
p5.Vector Object : [20, 30, 0]
      ✓ example #1 works
      ✓ example #2 works
    set documentation
      ✓ example #1 works
      ✓ example #2 works
    copy documentation
true
      ✓ example #1 works
    add documentation
      ✓ example #1 works
      ✓ example #2 works
(node:43277) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long
    at Promise (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/Connection.js:185:12)
    at JSHandle.jsonValue (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/ExecutionContext.js:239:43)
    at JSHandle.<anonymous> (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/helper.js:145:23)
    at v (/Users/dhowe/git/p5.js/tasks/test/mocha-chrome.js:48:61)
    at /Users/dhowe/git/p5.js/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
(node:43277) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43277) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      ✓ example #3 works
    sub documentation
      ✓ example #1 works
      ✓ example #2 works
(node:43277) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long
    at Promise (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/Connection.js:185:12)
    at JSHandle.jsonValue (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/ExecutionContext.js:239:43)
    at JSHandle.<anonymous> (/Users/dhowe/git/p5.js/node_modules/puppeteer/lib/helper.js:145:23)
    at v (/Users/dhowe/git/p5.js/tasks/test/mocha-chrome.js:48:61)
    at /Users/dhowe/git/p5.js/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/dhowe/git/p5.js/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
(node:43277) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
      ✓ example #3 works

```
</details>

**Comment by Spongman** [comment]
the first one is #3414

I was unable to determine the cause of the promise rejection warning. the surrounding tests all pass, and they fail correctly when altered.

**Comment by bishopZ** [comment]
I am getting this `texture()` error on any WEBGL sketch I run that includes `vertex()`.

Consider [this sketch](https://editor.p5js.org/bishopz/sketches/8LJDNbAQt) that takes it's code from [the documentation](https://p5js.org/reference/#/p5/vertex). Or [this sketch](https://editor.p5js.org/bishopz/sketches/vYmc0_PE5) taken from [this previous Github issue](https://github.com/processing/p5.js/issues/1071).

Is there something I am supposed to be doing? Any help appreciated.

**Comment by haschdl** [comment]
this looks like the same as reported in #3498 The issue has been fixed but not yet released.

**Comment by lmccart** [comment]
as @haschdl  mentions, this error has been addressed and is in the latest release.
