### ISSUE TITLE
Rendering text (WEBGL on Android)

### ISSUE THREAD

**Issue by matheusb-comp** [processing/p5.js#4404]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.10.2
- Web browser and version: Google Chrome 80.0.3987.119
- Operating System: Android 7.1.2 N2G47H
- Example Sketch: https://editor.p5js.org/matheusb-comp/sketches/b6NiYKQ5O

Using the [`text()`](https://p5js.org/reference/#/p5/text) function in a `WEBGL` canvas does not work on Google Chrome on my Android mobile phone.
Running the example sketch without the `text('A', 0, 0);` line, or running on the PC, it works as expected.

Also, the 3D Geometries [WEBGL example](https://p5js.org/examples/3d-geometries.html) works fine on the same phone.

The try-catches were added to the example sketch so the error would appear in the "console" window of the p5 editor page.

When running for the first time, the error happens when rendering the text:
```
DRAWING ERROR: Failed to execute 'useProgram' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
TypeError: Failed to execute 'useProgram' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
  at _main.default.Shader.useProgram (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:99060:16)
  at _main.default.Shader.bindShader (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:98934:20)
  at _main.default.RendererGL._renderText (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:100457:16)
  at _main.default.RendererGL._main.default.Renderer.text (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:60711:22)
  at p5._main.default.text (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:86021:57) at draw (about:srcdoc:84:5)
  at p5._main.default.redraw (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:65953:19)
  at _draw (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:58869:25)
```

Then, when trying to re-run the sketch, the `createCanvas` function stops working.
```
createCanvas: Error creating webgl context
Error: Error creating webgl context
  at _main.default.RendererGL._initContext (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:97427:23)
  at new _main.default.RendererGL (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:97283:18)
  at p5._main.default.createCanvas (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:62457:46)
  at setup (about:srcdoc:63:5) at _setup (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:58811:27)
  at _runIfPreloadsAreDone (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:58752:27)
  at p5._decrementPreload (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:58761:27)
  at https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:85901:20
  at https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:51698:26
  at XMLHttpRequest.request.onload (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js:51340:28)
```

<details>
   <summary>Phone screenshot</summary>

   ![p5_android_error](https://user-images.githubusercontent.com/1227961/77344828-85367900-6d12-11ea-8b7c-b487d2a2b012.jpg)
</details>

**Comment by stalgiag** [comment]
Hi @matheusb-comp thanks for the well-written issue!

I am unable to replicate on:
- Android 10 QKQ1.190825.002
- Chrome 80.0.3987.149

I see that you are using a relatively old Android OS. I am not sure if this is the issue but seems like the biggest difference between our phones.

Here is a screenshot of your sketch:
![Screenshot_2020-03-23-11-14-51-843_com android chrome](https://user-images.githubusercontent.com/10382506/77349447-43003e00-6cf8-11ea-977e-2a5e0bed8344.jpg)

**Comment by matheusb-comp** [comment]
Thanks for the response!
It really seems to be a problem on my phone. I thought it could be a bug in the library since it only happened when rendering text, while the geometries work.
But I tried on another phone with Android 9 and the sketch also works.

Sorry for the non-issue, but at least it will be registered, if anyone else runs at this problem.
