### ISSUE TITLE
loadImage() does't load a local image

### ISSUE THREAD

**Issue by dadepezzi** [processing/p5.js#4607]
Hello! I tried to load am image stored inside my project folder doing:
`img=loadImage('images/image1.jpg');`

but I got these errors:
`Fetch API cannot load file:///C:/Users/Davide/Desktop/project/images/image1.jpg. URL scheme must be "http" or "https" for CORS request.`
`TypeError: Failed to fetch
    at p5._main.default.loadImage (file:///C:/Users/Davide/Desktop/project/libs/p5.js:79330:13)
    at file:///C:/Users/Davide/Desktop/project/libs/p5.js:63012:67
    at preload (file:///C:/Users/Davide/Desktop/project/script.js:2:9)
    at p5._start (file:///C:/Users/Davide/Desktop/project/libs/p5.js:62970:19)
    at new p5 (file:///C:/Users/Davide/Desktop/project/libs/p5.js:63317:22)
    at _globalInit (file:///C:/Users/Davide/Desktop/project/libs/p5.js:62466:17)`

If I give it an URL it works tho.
Can I do the same thing but with local images instead?

**Comment by DivyamAhuja** [comment]
It's because of browser's CORS security policy , that you can't fetch files from same origin without running server. The only easy way I know to solve is by running local server using nodejs or something. There might be other easy and possible solutions

**Comment by dadepezzi** [comment]
@DivyamAhuja Thank you now it works!
