### ISSUE TITLE
need apikey for mailgun when deploy using docker

### ISSUE THREAD

**Issue by yonghuming** [processing/p5.js#4739]
i run 
```
docker run -it catarak/p5.js-web-editor
```
and then get error msg
```
root@iZbp17zvjg3zk5qn3yiotzZ:~/p5.js-web-editor# docker run -it catarak/p5.js-web-editor

> p5.js-web-editor@1.0.7 start:prod /usr/src/app
> cross-env NODE_ENV=production node index.js

/usr/src/app/node_modules/mailgun-js/lib/mailgun.js:16
      throw new Error('apiKey value must be defined!')
      ^

Error: apiKey value must be defined!
    at new Mailgun (/usr/src/app/node_modules/mailgun-js/lib/mailgun.js:16:13)
    at create (/usr/src/app/node_modules/mailgun-js/lib/mailgun.js:234:10)
    at new MailgunTransport (/usr/src/app/node_modules/nodemailer-mailgun-transport/src/mailgun-transport.js:52:18)
    at module.exports (/usr/src/app/node_modules/nodemailer-mailgun-transport/src/mailgun-transport.js:44:10)
    at new e (/usr/src/app/dist/server.bundle.js:1:22204)
    at Object.<anonymous> (/usr/src/app/dist/server.bundle.js:1:22039)
    at t (/usr/src/app/dist/server.bundle.js:1:110)
    at Object.<anonymous> (/usr/src/app/dist/server.bundle.js:1:37476)
    at t (/usr/src/app/dist/server.bundle.js:1:110)
    at Object.<anonymous> (/usr/src/app/dist/server.bundle.js:1:12306)
    at t (/usr/src/app/dist/server.bundle.js:1:110)
    at Object.<anonymous> (/usr/src/app/dist/server.bundle.js:1:51776)
    at t (/usr/src/app/dist/server.bundle.js:1:110)
    at Module.<anonymous> (/usr/src/app/dist/server.bundle.js:1:62293)
    at Module.<anonymous> (/usr/src/app/dist/server.bundle.js:1:64965)
    at t (/usr/src/app/dist/server.bundle.js:1:110)
    at Object.<anonymous> (/usr/src/app/dist/server.bundle.js:1:61988)
    at t (/usr/src/app/dist/server.bundle.js:1:110)
    at /usr/src/app/dist/server.bundle.js:1:902
    at Object.<anonymous> (/usr/src/app/dist/server.bundle.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! p5.js-web-editor@1.0.7 start:prod: `cross-env NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the p5.js-web-editor@1.0.7 start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-13T06_01_39_047Z-debug.log
root@iZbp17zvjg3zk5qn3yiotzZ:~/p5.js-web-editor#
root@iZbp17zvjg3zk5qn3yiotzZ:~/p5.js-web-editor#
root@iZbp17zvjg3zk5qn3yiotzZ:~/p5.js-web-editor#
root@iZbp17zvjg3zk5qn3yiotzZ:~/p5.js-web-editor# docker run -it catarak/p5.js-web-editordocker run -it catarak/p5.js-web-editor
Unable to find image 'catarak/p5.js-web-editordocker:latest' locally
docker: Error response from daemon: pull access denied for catarak/p5.js-web-editordocker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

```

**Comment by limzykenneth** [comment]
Hi @yonghuming, this is the repo for the library, this issue should be posted to the web editor's repo [here](https://github.com/processing/p5.js-web-editor/issues). Thanks.
