### ISSUE TITLE
loadSound() thinks its not defined

### ISSUE THREAD

**Issue by Kylomask** [processing/p5.js#5359]
so i hhad a really important project to submit but loadSound() dosent work, and i tried to fix it, nothing happened. Please fix.

**Comment by limzykenneth** [comment]
Hi @Kylomask, can you provide a bit more information about what's going on? We need to be able to replicate your problem or we won't be able to help here. Filling out the issue template will be really helpful for us. Thanks.

**Comment by Kylomask** [comment]
so i tried to use loadSound, i declared a variable and did all that with p5.sound.min.js but it says not defined

**Comment by Kylomask** [comment]
ReferenceError: loadSound is not defined
    at preload (/sketch.js:15:3)

    at p5._start (https://assets.editor.p5js.org/6092f1eb2385d600207318bf/eb5fec05-8e58-44ab-a5ad-015211a5f3da.js:48706:19)

    at new p5 (https://assets.editor.p5js.org/6092f1eb2385d600207318bf/eb5fec05-8e58-44ab-a5ad-015211a5f3da.js:49057:22)

    at _globalInit (https://assets.editor.p5js.org/6092f1eb2385d600207318bf/eb5fec05-8e58-44ab-a5ad-015211a5f3da.js:48197:17)

**Comment by limzykenneth** [comment]
Is the p5.sound.min.js script included in the HTML like below?

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/addons/p5.sound.min.js"></script>
```

**Comment by Kylomask** [comment]
no

**Comment by Kylomask** [comment]
should i put it in?

**Comment by Kylomask** [comment]
wait nevermind i found it

**Comment by Kylomask** [comment]
just, without the p5.sound.min.js, i used new Audio!
