### ISSUE TITLE
createObjectUrl error when adding more than 1 script to index.html

### ISSUE THREAD

**Issue by sosunnyproject** [processing/p5.js#5402]
#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering
- [x] DOM
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0 (same error happens on 1.0.0 version as well)
- Web browser and version: Tested both on Chrome and Brave browser. 1.29.77 Chromium: 93.0.4577.63 (Official Build) (64-bit)
- Operating System: , Windows 10 OS Version 2009 (Build 19043.1165) 
- Steps to reproduce this: example sketch is here https://editor.p5js.org/sosunnyproject/sketches/-x34Vskm4

When I add more than 1 script to HTML, it returns error. 
It seems like it cannot read more than one script src?
I tried with 0.10.2 version of p5js, and had no problem using two script sources. 
But when I tried with 1.0.0 and 1.4.0 version, it returned same error as below. 

Below is the error message I get when I run the sketch with 2 script sources.
```
TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at (anonymous function) (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/addons/p5.sound.min.js:2:98412)

    at p5.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/addons/p5.sound.min.js:2:98338)

    at p5.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js:63190:21)

    at new p5 (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js:63188:44)

    at _globalInit (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js:62189:17)
```

Please let me know if you need more explanation  or if someone's already working on this :)

**Comment by limzykenneth** [comment]
`Blob` is a reserved keyword in Javascript so you will need to rename the `Blob` class you have to something else.
