### ISSUE TITLE
 CI Test Failing Around saveGif Documentation After Merging Markdown File

### ISSUE THREAD

**Issue by SableRaf** [processing/p5.js#6465]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [X] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

n/a

### Web browser and version

n/a

### Operating System

n/a

### Description
After merging [This Markdown file](https://github.com/processing/p5.js/blob/main/contributor_docs/project_wrapups/munusshih_gsoc_2023.md), a CI test began failing. The issue seems to revolve around the saveGif documentation (see the log below). 

### Expected behavior
All CI checks should pass without errors after merging a Markdown file that is unrelated to codebase functionality.

### CI Run Log
```
1 failing
  954 passing (39s)
  1) src/image/loading_displaying.js
       saveGif documentation
         example #1 works:
     TypeError: Cannot read properties of null (reading 'insertAdjacentHTML')
      at _main.default._describeHTML (http://localhost:9001/lib/p5.js:5[2184](https://github.com/processing/p5.js/actions/runs/6451897549/job/17513145355#step:5:2185):73)
      at _main.default.describe (http://localhost:9001/lib/p5.js:52034:18)
      at p5.draw (eval at <anonymous> (test-reference.html:36:11), <anonymous>:7:3)
      at p.<computed> (test-reference.html:153:27)
      at p.draw (test-reference.html:165:27)
      at _main.default.redraw (http://localhost:9001/lib/p5.js:70928:25)
      at _draw (http://localhost:9001/lib/p5.js:62374:23)

Warning: [object Object] Use --force to continue.

Aborted due to warnings.
Error: Process completed with exit code 3.
``` 

Full log: https://github.com/processing/p5.js/actions/runs/6451897549/job/17513145355

**Comment by davepagurek** [comment]
It looks like some commits afterward pass, do you think it was just a flake?

![image](https://github.com/processing/p5.js/assets/5315059/290f014d-ad4d-4d1d-b807-419f30a91089)

**Comment by Qianqianye** [comment]
I think @limzykenneth probably helped re-run the test an hour ago, which cleared the testing failure. Are there any test optimizations we should do to avoid this problem in the future?

**Comment by limzykenneth** [comment]
Looking into the code I think the line that is failing may be [this line](https://github.com/processing/p5.js/blob/main/src/accessibility/describe.js#L256) but I don't understand why it is timing dependent nor why it appear to consistently happen on `saveGif()`'s example test, when its example is not doing anything vastly different from the other examples.

I also don't see where `#${cnvId}accessibleOutput` id is assigned to make the code reach that line so I'm even less clear how the code execution even got to that point in the first place. Will need someone with a bit more insight into the web accessiblity stuff to have a look probably.
