### ISSUE TITLE
When bundling p5 with React using create-vite-app, you get a build error

### ISSUE THREAD

**Issue by themonk911** [processing/p5.js#6626]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Steps:
1. Create a vite app
2. Add p5 to the package.json
3. Run npm run build

### Snippet:
Here's a snippet from my package.json.
```js

 "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "deploy": "gh-pages -d dist"
  },
  "dependencies": {
    "eslint-import-resolver-alias": "^1.1.2",
    "fuse.js": "^7.0.0",
    "p5": "^1.9.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-modal": "^3.16.1"
  },

```
Here's the resulting error message.

error during build:
RollupError: Identifier "r" has already been declared
    at error (file://.../node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file://.../node_modules/rollup/dist/es/shared/node-entry.js:12728:16)
    at BlockScope.addDeclaration (file://.../node_modules/rollup/dist/es/shared/node-entry.js:7522:32)
    at Identifier.declare (file://.../node_modules/rollup/dist/es/shared/node-entry.js:7193:39)
    at VariableDeclarator.declareDeclarator (file://.../node_modules/rollup/dist/es/shared/node-entry.js:10169:17)
    at VariableDeclaration.initialise (file://.../node_modules/rollup/dist/es/shared/node-entry.js:11834:24)
    at new NodeBase (file://.../node_modules/rollup/dist/es/shared/node-entry.js:4607:14)
    at new VariableDeclaration (file://.../node_modules/rollup/dist/es/shared/node-entry.js:11806:1)
    at BlockStatement.parseNode (file://.../node_modules/rollup/dist/es/shared/node-entry.js:4718:27)
    at new NodeBase (file://.../node_modules/rollup/dist/es/shared/node-entry.js:4606:14)

**Comment by limzykenneth** [comment]
p5.js is not currently designed to be bundled as part of your code in this way. We are investigating updating it but it will take time to fully migrate. The recommended way to use p5.js is through a `<script>` tag include and accessing the `p5` contructor in your code.

**Comment by arghaDEVIL** [comment]
The error message you're encountering is a RollupError indicating that the identifier "r" has already been declared. This typically happens when you have a variable, function, or some other identifier named "r" declared more than once in the same scope.
Review your code to identify where the identifier "r" is declared. Look for duplicate declarations of the same identifier within the same scope.

**Comment by Vaivaswat2244** [comment]
Hey @themonk911, I tested this with several Vite/Rollup versions and could not reproduce the error. It appears this was a bug in early Rollup 4.x releases that has since been patched upstream — the parseAst.js path in the stacktrace was part of Rollup's new Rust-based parser introduced in v4, which had instability in its early releases. [link](https://github.com/rollup/rollup/blob/cc0f51af8e06aec3ca5f191c7863fb065527e2e9/CHANGELOG.md?plain=1#L2447-L2454)


Both p5@1.9.0 and p5@2.x bundle cleanly with current Vite (4, 5, and 8). If anyone is still hitting this, please share your exact Rollup/Vite version — but given the age of this issue and upstream fixes, I think this should be closed. @ksen0 

<img width="1405" height="974" alt="Image" src="https://github.com/user-attachments/assets/e1cb0cdb-fa7d-48b9-a867-c9d41ff0181c" />

**Comment by limzykenneth** [comment]
Closed as current 2.x supports Vite and ESM usage officially. Please do open a new issue for any problems with it.
