### ISSUE TITLE
Allow p5 classes (like `p5.Color`, `p5.Vector` etc.) to be used outside of the browser (node, deno, bun etc.)?

### ISSUE THREAD

**Issue by RobinBoers** [processing/p5.js#6830]
### Topic

Hi, I'm building a multiplayer game using p5js. I would like to use the same classes for vectors and colors etc (like `p5.Color`, `p5.Vector`) on the server-side as on the frondend, but when I include them like this:

```javascript
import { Color, Vector } from "p5";
```

I get the following error:

```
ReferenceError: Can't find variable: window
      at /home/robin/projects/102/node_modules/p5/lib/p5.min.js:2:541617
      at a (/home/robin/projects/102/node_modules/p5/lib/p5.min.js:2:513)
      at /home/robin/projects/102/node_modules/p5/lib/p5.min.js:2:555
      at /home/robin/projects/102/node_modules/p5/lib/p5.min.js:2:458110
```

I'm starting the server like this:

```bash
bun run src/server/main.ts
```

I think it would be cool to be able to use the classes that don't necessarily need the browser/canvas outside on other places too.

Maybe I'm just really dum and this is already possible? I also completely understand if this is out of scope for p5js, but I thought I'd ask :)

I can also split these classes into a seperate library/NPM package.

**Comment by limzykenneth** [comment]
@RobinBoers The current internal design of p5.js does not account for internal classes to be used like this, although I agree that it will likely be useful to have. We are currently exploring what the next major version of p5.js would be and I have some plans for redesigning how internal modules work. I can certainly look into incorporating this idea potentially. 2.0 is still a bit of a long way away though, so this will not be something you will be able to do very soon.

**Comment by RobinBoers** [comment]
Hi @limzykenneth, thank you for the quick response. I think I'll just create a seperate package  containing just `p5.Vector` and `p5.Color` for now.

**Comment by limzykenneth** [comment]
@RobinBoers If you got something working, do share and I may base future work on what you have. Thanks.

**Comment by kjhollen** [comment]
Another side effect of this could be making it easier to work with color in p5.js in general. Right now, it's not possible to put a simple assignment statement like this in the global scope of a sketch:

`let c = color(255, 128, 128);`

in the global scope. This produces an error, and is a difficult technicality to explain to beginner students. If this request could also fix this issue, I think it would be a lot easier to teach/learn how to work with color in p5.

**Comment by dhowe** [comment]
any further discussion/thinking on supporting basic classes (color, vector, font) outside of the p5 context ?

**Comment by RobinBoers** [comment]
I got something very basic working for my game project.

p5.Vector works (which was my main use case, as I'm calculating physics on the server), but p5.Color depended on some internal magic, if I remember correctly. So I just gave up and ended up passing hexidecimal color strings back and forth between the client and server.

http://git.dupunkto.org/forks/p5-node/

**Comment by limzykenneth** [comment]
@dhowe There hasn't been much yet but it is something I am still interested in exploring for p5.js 2.0. With additional interest and discussion from the community there probably can be a more fleshed out idea.

My current thinking is that for the math/numerical stuff it is relatively straightforward to do, however for things like p5.Color where my current idea is to leverage CSS where possible or p5.Font where I would prefer to leverage browser implementation as much as possible, a version that needs to be used outside of the browser will need its own implementation of those features where we lean on browser implementations. 2.0 will likely introduce flexibility to patch different versions of different use case but the actual implementation of either case I still have not had the chance to work out.

**Comment by RobinBoers** [comment]
❤️🧡💛💚💙💜

**Comment by L1lith** [comment]
The lack of support for server side runtimes is a major issue for me because I'm doing isomorphic rendering with [Astro](https://astro.build/). While it would be cool to be able to automatically pre-render the splash screen, the poor support for non-browser is causing my build to fail at import step even despite the fact that I am not even attempting to render the game on the server. I believe this to be a major design flaw that should be fixed even before full non-browser support is added. Here is the current error message though there may be more behind it:

```
Exception during run: SyntaxError: The requested module 'gifenc' does not provide an export named 'GIFEncoder'
```

I also think it would be better design to avoid doing any heavy lifting that requires Browser APIs automatically at package load, and instead should be deferred until P5.js initialization has been manually triggered by the developer.

@ksen0 would you be able to add partial support like this before full support to prevent crashing the server build process? (particularly support for importing without actually calling any P5.js methods). Also this issue seems to have fallen off the radar considering 2.0 has already been released.

**Comment by limzykenneth** [comment]
@L1lith @ksen0 This should be fixed with #8357. @L1lith If you can try out the PR version with `https://pkg.pr.new/p5@594c74f` in your package.json dependency then let me know if it is working or not that would be great, otherwise a minimal replication repo would be very helpful as well.

**Comment by L1lith** [comment]
> [@L1lith](https://github.com/L1lith) [@ksen0](https://github.com/ksen0) This should be fixed with [#8357](https://github.com/processing/p5.js/pull/8357). [@L1lith](https://github.com/L1lith) If you can try out the PR version with `https://pkg.pr.new/p5@594c74f` in your package.json dependency then let me know if it is working or not that would be great, otherwise a minimal replication repo would be very helpful as well.

Hello, thanks for the swift response! Unfortunately it is still malfunctioning. The error is different this time. I have also created a minimal reproduction repo for you. I have also included instructions on how to launch the web app in the repo readme.

The Minimal Reproduction Repo URL: https://github.com/L1lith/P5.JS-Astro-NodeJS-Compatibility-Test

The Current Error
```
ReferenceError: window is not defined
    at fesCore (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/p5/dist/core/friendly_errors/fes_core.js:945:5)
    at p5.registerAddon (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/p5/dist/main-DF-ynVCz.js:1447:5)
    at friendlyErrors (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/p5/dist/core/friendly_errors/index.js:16:6)
    at file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/p5/dist/app.js:126:1
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)
    at async ModuleRunner.directRequest (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:1109:20)
    at async ModuleRunner.cachedRequest (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\src\components\P5Test.jsx:1:1)
    at async ESModulesEvaluator.runInlinedModule (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:913:3)
    at async ModuleRunner.directRequest (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async ModuleRunner.cachedRequest (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\src\pages\index.astro:2:1)
    at async ESModulesEvaluator.runInlinedModule (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:913:3)
    at async ModuleRunner.directRequest (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async ModuleRunner.cachedRequest (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async ModuleRunner.import (file:///C:/Users/05L1/Projects/p5-js-isomorphic-compatibility-test/node_modules/vite/dist/node/module-runner.js:1014:10)
    at async RunnablePipeline.preload (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\node_modules\astro\dist\vite-plugin-app\pipeline.js:141:14)
    at async RunnablePipeline.getComponentByRoute (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\node_modules\astro\dist\vite-plugin-app\pipeline.js:154:12)
    at async matchRoute (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\node_modules\astro\dist\core\routing\dev.js:17:14)
    at async AstroServerApp.devMatch (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\node_modules\astro\dist\vite-plugin-app\app.js:60:26)
    at async run (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\node_modules\astro\dist\vite-plugin-app\app.js:136:30)
    at async runWithErrorHandling (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\node_modules\astro\dist\vite-plugin-astro-server\controller.js:64:5)
    at async AstroServerApp.handleRequest (C:\Users\05L1\Projects\p5-js-isomorphic-compatibility-test\node_modules\astro\dist\vite-plugin-app\app.js:132:5)
```

**Comment by L1lith** [comment]
The changes in PR https://github.com/processing/p5.js/pull/8357 seem to have fixed the issues with the server crashing upon importing, this is great! I would like if there could be full support for the library in server side environments. I think there's plenty of libraries that could spoof the canvas API or other browser APIs, though it may not be as simple as that. I hope that the import issue fix can be published on NPM sometime soon 😄 

In the future I think putting a screenshot of the first frame of the game while the rest of the game is loading could be an awesome way to start doing isomorphic game loading! Another approach could be maybe doing a gif of the first X number of frames and have them play. For now though I think just fixing the import issue is great.

**Comment by limzykenneth** [comment]
@L1lith To test #8357 and some early exploration into server side usage I've made [p5.term.js](https://github.com/limzykenneth/p5.term.js) as an experiment. For full rendering on the server I'm not very keen on libraries that replicate the canvas API but there are things in the works in the mid to long term, suffice it to say it is a goal to have it run and render in a server side environment in the future.
